### ISSUE TITLE
Adding a readme English Translated File, HacktoberFest 2K23

### ISSUE THREAD

**Issue by HartzFrequency** [tiagocordeiro/pyassinamail#229]
hey @tiagocordeiro 
I want to add a english readme file 
which will help global audience to contribute to your project
please assign it to me, and relevant Labels
Thank you

**Comment by tiagocordeiro** [comment]
Thank you for your willingness to help! I've assigned the task to you. Your contribution will be valuable in making the project accessible to a global audience. Thanks again!
